package com.encore.ticket.core.booking.exception;

public enum BookingErrorCode {

    QUEUE_NOT_ADMITTED,
    QUEUE_TOKEN_NOT_OWNED,
    HOLD_NOT_OWNED,
    RESERVATION_NOT_OWNED,
    SEAT_ALREADY_HELD,
    IDEMPOTENCY_KEY_REUSED,
    PURCHASE_LIMIT_EXCEEDED,
    RESERVATION_CANCELLED,
    RESERVATION_CONCURRENTLY_MODIFIED,
    CANCELLATION_CLOSED,
    PAYMENT_IN_PROGRESS,
    HOLD_EXPIRED,
    QUEUE_TOKEN_EXPIRED
}
